" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

"字体
set guifont=Consolas:h20:cGB2312
"显示行数
set nu!
"关闭兼容
set nocompatible
syntax on
"括号匹配
set showmatch
"set smartindent
"开启代码折叠
set foldenable
"tab按键的空格数
set tabstop=4
"显示光标列数
set ruler
"自动缩进
set autoindent 

"键盘映射
imap jk <Esc>
nmap jk <Esc>
map ti :tabe.<cr>
"设置背景颜色
colorscheme desert
set virtualedit=block,onemore

set noundofile
set nobackup
set noswapfile

"默认显示编码
set enc=gbk
"根据这里的编码自动检测
set fencs=utf-8,gbk,big5,cp936,gb18030,gb2312,utf-16
"保存文件编码
set fenc=gbk
"关闭错误提示音
set vb t_vb=

